### ISSUE TITLE
「公告」全站CSS错误

### ISSUE THREAD

**Issue by kdxiaoyi** [kdxiaoyi/kdxiaoyi.github.io#5]
2023-03-04 17:50左右，我发现全站CSS不正常
2023-03-04 18:13左右，发现子仓库所绑定的域名(kdx.a  wa.cf)被GFW ban了

现已更换其它域名

**Comment by kdXiaoyi** [comment]
https://github.com/kdX233/kdx233.github.io/commit/4711199bdbd4c0e7208889c283723d3dd64b436c
已提交修复

**Comment by kdXiaoyi** [comment]
梅开二度更新：https://github.com/kdX233/kdx233.github.io/commit/4cf8ed4ce4622d6bd84d0a47a87ba2a319d83635
